In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt
import networkx as nx
import copy

In [22]:
X = torch.tensor([[[1,0], [0, 1]], [[1,0], [1,1]], [[1,0], [0, -1]]])
Y = torch.tensor([[[1, 0, -1], [0, 2, -2]], [[1,1,0], [2,0,2]]])
print(X)
print(Y)

tensor([[[ 1,  0],
         [ 0,  1]],

        [[ 1,  0],
         [ 1,  1]],

        [[ 1,  0],
         [ 0, -1]]])
tensor([[[ 1,  0, -1],
         [ 0,  2, -2]],

        [[ 1,  1,  0],
         [ 2,  0,  2]]])


In [13]:
print(X.shape)
print(Y.shape)
torch.tensordot(X, Y, dims=([1], [1]))

torch.Size([3, 2, 2])
torch.Size([2, 2, 3])


tensor([[[[ 1,  0, -1],
          [ 1,  1,  0]],

         [[ 0,  2, -2],
          [ 2,  0,  2]]],


        [[[ 1,  2, -3],
          [ 3,  1,  2]],

         [[ 0,  2, -2],
          [ 2,  0,  2]]],


        [[[ 1,  0, -1],
          [ 1,  1,  0]],

         [[ 0, -2,  2],
          [-2,  0, -2]]]])

In [21]:
torch.reshape(torch.permute(X, (0, 2, 1)), (6, 2))

tensor([[ 1,  0],
        [ 0,  1],
        [ 1,  1],
        [ 0,  1],
        [ 1,  0],
        [ 0, -1]])

In [23]:
torch.reshape(torch.permute(Y, (1,0,2)), (2, 6))

tensor([[ 1,  0, -1,  1,  1,  0],
        [ 0,  2, -2,  2,  0,  2]])